# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: build/schema

jobs:
# Please do not rename this job
  build-project:
    name: build daruapi
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v14.21.3

      - name: Build Node assets
        env:
          CI: true
          CLIENT_URL: https://daru.mx/
          DATABASE: mongodb+srv://admindaru:09Fj1973@darudb.pyr0hie.mongodb.net/darushopdev
          SECRET: daru-ecommerce-09Fj1973
          SITE_URL: ${{ inputs.site-url }}
          STRIPE_API_KEY: sk_test_51LcAKpKmpYSfXVu37hEWbmCaZ1VOfKGMQk9ZGjScEMtKm9c8yS3ENv695dGVK5522QyjQhoXw9rBUnUvUfgvYsuq004bHP5rZn
          STRIPE_API_VERSION: 2022-08-01
          UPLOAD_URL: https://api.daru.mx/uploads
          USER_EMAIL: fjpimienta@hosting3m.com
          USER_PASSWORD: 09Fj1973!!
        run: |
          npm ci
          npm run start

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 5d9d8edc-857a-4290-99d0-fe73ed8e3f1d
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/daruapi/config.yaml
          action: upload
